export const iconStyles = {
  arrowLeft: {
    width: "16px",
    height: "16px",
    display: "inline-block",
    marginRight: "8px",
  },
  plus: {
    width: "16px",
    height: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    fontWeight: "bold",
  },
  x: {
    width: "14px",
    height: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: "bold",
  },
  xLarge: {
    width: "16px",
    height: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    fontWeight: "bold",
  },
  save: {
    width: "16px",
    height: "16px",
    display: "inline-block",
    marginRight: "8px",
  },
  icon: {
    width: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  successIcon: {
    border: "2px solid white",
    borderRadius: "50%",
    position: "relative",
  },
  checkmark: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    fontSize: "12px",
    fontWeight: "bold",
  },
  alertIcon: {
    border: "2px solid white",
    borderRadius: "50%",
    position: "relative",
  },
  alertDot: {
    position: "absolute",
    top: "25%",
    left: "50%",
    transform: "translateX(-50%)",
    fontSize: "14px",
    fontWeight: "bold",
  },
  alertLine: {
    position: "absolute",
    bottom: "25%",
    left: "50%",
    transform: "translateX(-50%)",
    fontSize: "14px",
    fontWeight: "bold",
  },
  chevronLeft: {
    width: "16px",
    height: "16px",
    border: "solid currentColor",
    borderWidth: "0 2px 2px 0",
    display: "inline-block",
    padding: "3px",
    transform: "rotate(135deg)",
    marginLeft: "3px",
  },
  chevronRight: {
    width: "16px",
    height: "16px",
    border: "solid currentColor",
    borderWidth: "0 2px 2px 0",
    display: "inline-block",
    padding: "3px",
    transform: "rotate(-45deg)",
    marginRight: "3px",
  },
  edit: {
    position: "relative",
    display: "inline-block",
    width: "18px",
    height: "18px",
  },
  trash: {
    position: "relative",
    display: "inline-block",
    width: "18px",
    height: "18px",
  },
};

export default iconStyles;
