export const loginStyles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'system-ui, sans-serif',
    padding: '20px',
  },
  mainCard: {
    display: 'flex',
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    overflow: 'hidden',
    maxWidth: '900px',
    width: '100%',
    minHeight: '500px',
  },
  leftPanel: {
    backgroundColor: '#4A90E2',
    color: 'white',
    padding: '40px',
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  welcomeTitle: {
    fontSize: '28px',
    fontWeight: 'bold',
    marginBottom: '20px',
    lineHeight: '1.2',
  },
  subtitle: {
    fontSize: '16px',
    marginBottom: '30px',
    lineHeight: '1.4',
    opacity: '0.9',
  },
  featureList: {
    listStyle: 'none',
    padding: '0',
    margin: '0 0 40px 0',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '15px',
    fontSize: '16px',
  },
  checkIcon: {
    marginRight: '12px',
    fontSize: '18px',
    color: '#90CDF4',
  },
  buildingIcon: {
    textAlign: 'center',
    fontSize: '80px',
    opacity: '0.8',
  },
  rightPanel: {
    padding: '40px',
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  loginTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#4A90E2',
    textAlign: 'center',
    marginBottom: '30px',
  },
  formGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontSize: '16px',
    fontWeight: '500',
    color: '#374151',
  },
  input: {
    width: '100%',
    padding: '12px',
    border: '2px solid #d1d5db',
    borderRadius: '4px',
    fontSize: '16px',
    outline: 'none',
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
  },
  inputFocus: {
    borderColor: '#4A90E2',
  },
  loginButton: {
    width: '100%',
    backgroundColor: '#4A90E2',
    color: 'white',
    border: 'none',
    padding: '12px',
    borderRadius: '4px',
    fontSize: '16px',
    fontWeight: '500',
    cursor: 'pointer',
    marginBottom: '20px',
    transition: 'background-color 0.2s',
  },
  loginButtonHover: {
    backgroundColor: '#357ABD',
  },
  forgotPassword: {
    textAlign: 'center',
    marginBottom: '30px',
  },
  forgotPasswordLink: {
    color: '#4A90E2',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: '14px',
  },
  errorMessage: {
    color: '#EF4444',
    fontSize: '14px',
    textAlign: 'center',
    marginTop: '10px',
    padding: '8px',
    backgroundColor: '#FEE2E2',
    borderRadius: '4px',
    border: '1px solid #FECACA',
  },

};

export default loginStyles;