export const styles = {
    container: {
      padding: '24px',
      maxWidth: '1200px',
      margin: '0 auto',
      fontFamily: 'system-ui, sans-serif',
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      marginBottom: '16px',
    },
    headerButton: {
      display: 'flex',
      alignItems: 'center',
      color: '#4B5563',
      marginRight: '16px',
      background: 'none',
      border: 'none',
      cursor: 'pointer',
    },
    headerButtonText: {
      marginLeft: '4px',
    },
    spacer: {
      flexGrow: 1,
    },
    actionButton: {
      background: '#E5E7EB',
      padding: '4px 12px',
      borderRadius: '4px',
      marginRight: '8px',
      border: 'none',
      cursor: 'pointer',
    },
    closeButton: {
      color: '#4B5563',
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      fontSize: '16px',
    },
    heading: {
      fontSize: '24px',
      fontWeight: 'bold',
      marginBottom: '16px',
    },
    searchContainer: {
      display: 'flex',
      justifyContent: 'space-between',
      marginBottom: '24px',
    },
    searchInput: {
      border: '1px solid #D1D5DB',
      borderRadius: '4px',
      padding: '8px',
      width: '250px',
    },
    searchButton: {
      background: '#3B82F6',
      color: 'white',
      padding: '8px 16px',
      borderRadius: '4px',
      marginLeft: '8px',
      border: 'none',
      cursor: 'pointer',
    },
    newButton: {
      background: '#10B981',
      color: 'white',
      padding: '8px 16px',
      borderRadius: '4px',
      border: 'none',
      cursor: 'pointer',
    },
    filtersContainer: {
      marginBottom: '24px',
      border: '1px solid #D1D5DB',
      borderRadius: '8px',
      padding: '16px',
      background: '#F9FAFB',
    },
    filtersTitle: {
      fontSize: '18px',
      fontWeight: '500',
      marginBottom: '8px',
    },
    filtersGrid: {
      gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
      gap: '20px',
      display: 'flex',
      width: '50%',
      justifyContent: 'space-between',
      alignItems: 'center'
    },
    formGroup: {
     marginBottom: '12px'
    },
    label: {
      display: 'block',
      marginBottom: '4px',
      fontSize: '14px',
      fontWeight: '500',
    },
    select: {
      border: '1px solid #D1D5DB',
      borderRadius: '4px',
      padding: '8px',
      width: '100%',
      fontSize: '14px',
    },
    buttonGroup: {
      display: 'flex',
      alignItems: 'flex-end',
      justifyContent: 'flex-end' 
    },
    applyButton: {
      background: '#3B82F6',
      color: 'white',
      padding: '8px 16px',
      borderRadius: '4px',
      marginRight: '8px',
      border: 'none',
      cursor: 'pointer',
      fontSize: '14px',
    },
    resetButton: {
      background: '#E5E7EB',
      padding: '8px 16px',
      borderRadius: '4px',
      border: 'none',
      cursor: 'pointer',
      fontSize: '14px',
    },
    tableContainer: {
      overflowX: 'auto',
    },
    table: {
      minWidth: '100%',
      backgroundColor: 'white',
      borderCollapse: 'collapse',
    },
    tableHead: {
      borderBottom: '1px solid #E5E7EB',
    },
    tableHeadCell: {
      padding: '8px 16px',
      textAlign: 'left',
      fontWeight: '500',
    },
    tableRow: {
      borderBottom: '1px solid #E5E7EB',
    },
    tableRowHover: {
      backgroundColor: '#F9FAFB',
    },
    tableCell: {
      padding: '8px 16px',
    },
    truncateText: {
      width: '150px',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    badgeObligatoria: {
      padding: '4px 8px',
      borderRadius: '4px',
      backgroundColor: '#DBEAFE',
      color: '#1E40AF',
      display: 'inline-block',
    },
    badgeOptativa: {
      padding: '4px 8px',
      borderRadius: '4px',
      backgroundColor: '#F3E8FF',
      color: '#6B21A8',
      display: 'inline-block',
    },
    correlativaChip: {
      background: '#F3F4F6',
      color: '#374151',
      padding: '4px 8px',
      borderRadius: '4px',
      marginBottom: '4px',
      display: 'inline-block',
      marginRight: '4px',
    },
    correlativaMore: {
      color: '#3B82F6',
      fontWeight: '500',
    },
    statusActive: {
      padding: '4px 8px',
      borderRadius: '4px',
      backgroundColor: '#D1FAE5',
      color: '#065F46',
      display: 'inline-block',
    },
    statusInactive: {
      padding: '4px 8px',
      borderRadius: '4px',
      backgroundColor: '#FEE2E2',
      color: '#991B1B',
      display: 'inline-block',
    },
    actionButtonsContainer: {
      display: 'flex',
      gap: '8px',
    },
    editButton: {
      color: '#FBBF24',
      background: 'none',
      border: 'none',
      cursor: 'pointer',
    },
    deleteButton: {
      color: '#EF4444',
      background: 'none',
      border: 'none',
      cursor: 'pointer',
    },
    pagination: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: '16px',
    },
    paginationNav: {
      display: 'flex',
      alignItems: 'center',
    },
    paginationButton: {
      border: '1px solid #D1D5DB',
      padding: '4px 8px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
    },
    paginationButtonDisabled: {
      opacity: '0.5',
      cursor: 'not-allowed',
    },
    paginationButtonLeft: {
      borderTopLeftRadius: '4px',
      borderBottomLeftRadius: '4px',
    },
    paginationButtonRight: {
      borderTopRightRadius: '4px',
      borderBottomRightRadius: '4px',
    },
    paginationPageButton: {
      border: '1px solid #D1D5DB',
      borderLeft: 'none',
      borderRight: 'none',
      padding: '4px 12px',
      backgroundColor: 'white',
    },
    paginationPageButtonActive: {
      backgroundColor: '#3B82F6',
      color: 'white',
    },
    formContainer: {
      backgroundColor: 'white',
      borderRadius: '8px',
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      padding: '24px',
      marginBottom: '24px',
    },
    formGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '20px',
    },
   
    formGroupFullWidth: {
      marginBottom: '12px',
      gridColumn: '1 / span 2',
    },
   
    input: {
      border: '1px solid #D1D5DB',
      borderRadius: '4px',
      padding: '8px',
      width: '100%',
      fontSize: '14px',
    },
    textarea: {
      border: '1px solid #D1D5DB',
      borderRadius: '4px',
      padding: '8px',
      width: '100%',
      fontSize: '14px',
      minHeight: '100px',
      resize: 'vertical',
    },
    correlativasContainer: {
      marginTop: '8px',
      display: 'flex',
      flexWrap: 'wrap',
      gap: '8px',
    },
   
    correlativaRemoveButton: {
      background: 'none',
      border: 'none',
      color: '#6B7280',
      marginLeft: '4px',
      cursor: 'pointer',
      padding: '0',
      display: 'flex',
      alignItems: 'center',
    },
    addCorrelativaContainer: {
      display: 'flex',
      marginTop: '8px',
    },
    addCorrelativaInput: {
      border: '1px solid #D1D5DB',
      borderRadius: '4px',
      padding: '8px',
      flexGrow: 1,
      marginRight: '8px',
    },
    addCorrelativaButton: {
      background: '#3B82F6',
      color: 'white',
      padding: '8px',
      borderRadius: '4px',
      border: 'none',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },

    cancelButton: {
      background: '#E5E7EB',
      padding: '8px 16px',
      borderRadius: '4px',
      border: 'none',
      cursor: 'pointer',
      fontSize: '14px',
      marginRight: '8px',
    },
    saveButton: {
      background: '#10B981',
      color: 'white',
      padding: '8px 16px',
      borderRadius: '4px',
      border: 'none',
      cursor: 'pointer',
      fontSize: '14px',
      display: 'flex',
      alignItems: 'center',
    },
    saveButtonIcon: {
      marginRight: '8px',
    },
  };

  export default styles;